"""initial schema

Revision ID: 820f7fe778b4
Revises: 
Create Date: 2026-09-02 17:51:29.340184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '820f7fe778b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('trading_name', sa.String(), nullable=True),
    sa.Column('entity_type', sa.Enum('SOLE_PROP', 'PARTNERSHIP', 'LTD', 'NGO', name='entitytype'), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('tin', sa.String(), nullable=True),
    sa.Column('sector_code', sa.String(length=2), nullable=True),
    sa.Column('established_on', sa.Date(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('premises_status', sa.String(), nullable=True),
    sa.Column('employee_count_declared', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('role', sa.Enum('OWNER', 'REVIEWER', 'ADMIN', name='role'), nullable=False),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('MOMO', 'BANK', 'POS', 'CASH_BOOK', name='accountkind'), nullable=False),
    sa.Column('provider', sa.Enum('MTN', 'TELECEL', 'AT', 'GCB', 'FIDELITY', 'ABSA', 'STANBIC', 'ECOBANK', 'CBG', 'OTHER_BANK', name='provider'), nullable=False),
    sa.Column('identifier_hash', sa.String(), nullable=False),
    sa.Column('display_suffix', sa.String(length=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_business_use', sa.Boolean(), nullable=True),
    sa.Column('ownership_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'identifier_hash', name='uq_account_business_identifier')
    )
    op.create_table('agent_session',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_before', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_after', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_event',
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_event',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('cost_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counterparty',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('msisdn_hash', sa.String(), nullable=True),
    sa.Column('kind', sa.Enum('CUSTOMER', 'SUPPLIER', 'STAFF', 'LENDER', 'TAX', 'SELF', 'UNKNOWN', name='counterpartykind'), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('txn_count', sa.Integer(), nullable=False),
    sa.Column('total_in_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('total_out_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.Enum('MOMO_STATEMENT', 'MOMO_MERCHANT_STATEMENT', 'BANK_STATEMENT', 'INVOICE_ISSUED', 'INVOICE_RECEIVED', 'RECEIPT', 'INFORMAL_LEDGER', 'REGISTRATION_CERT', 'TAX_DOC', 'TENANCY_AGREEMENT', 'STOCK_LIST', 'FINANCIAL_STATEMENT', 'CASHFLOW_PROJECTION', 'ID_DOCUMENT', 'OTHER', name='doctype'), nullable=True),
    sa.Column('doc_type_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('issuer', sa.Enum('MTN', 'TELECEL', 'AT', 'GCB', 'FIDELITY', 'ABSA', 'STANBIC', 'ECOBANK', 'CBG', 'OTHER_BANK', name='provider'), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'CLASSIFIED', 'EXTRACTED', 'RECONCILIATION_FAILED', 'FAILED', 'SUPERSEDED', name='docstatus'), nullable=False),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'sha256', name='uq_document_business_sha256')
    )
    op.create_table('gap',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('MISSING_DOCUMENT', 'MISSING_PERIOD', 'UNEXPLAINED_TXN', 'AMBIGUOUS_CATEGORY', 'INCONSISTENCY', 'MISSING_FACT', name='gapkind'), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKER', 'MAJOR', 'MINOR', name='gapseverity'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('target_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ANSWERED', 'DOCUMENT_RECEIVED', 'WAIVED', 'RESOLVED', name='gapstatus'), nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicator',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('formula_version', sa.String(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'code', 'period_start', 'period_end', 'formula_version', name='uq_indicator_business_code_period_version')
    )
    op.create_table('readiness_score',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rubric_version', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('band', sa.Enum('NOT_READY', 'DEVELOPING', 'NEARLY_READY', 'LENDER_READY', name='band'), nullable=False),
    sa.Column('pillars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_message',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_item',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('rule_pack_id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('requirement', sa.String(), nullable=False),
    sa.Column('condition_expr', sa.String(), nullable=True),
    sa.Column('constraint_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('satisfied_by_document_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['satisfied_by_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('declaration',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('gap_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('parsed_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asked_by', sa.String(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['gap_id'], ['gap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extraction',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.String(), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extractor', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('direction', sa.Enum('IN', 'OUT', name='direction'), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('fee_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('levy_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_pesewas', sa.BigInteger(), nullable=True),
    sa.Column('counterparty_raw', sa.String(), nullable=True),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('category_l1', sa.String(), nullable=True),
    sa.Column('category_l2', sa.String(), nullable=True),
    sa.Column('category_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('category_source', sa.Enum('RULE', 'KNN', 'LLM', 'HUMAN', 'OWNER_STATED', name='categorysource'), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_pesewas > 0', name='ck_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider_reference', name='uq_transaction_account_provider_reference')
    )
    op.create_index('ix_transaction_account_occurred_amount', 'transaction', ['account_id', 'occurred_on', 'amount_pesewas'], unique=False)
    op.create_index('ix_transaction_business_category', 'transaction', ['business_id', 'category_l1'], unique=False)
    op.create_index('ix_transaction_business_occurred', 'transaction', ['business_id', 'occurred_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_business_occurred', table_name='transaction')
    op.drop_index('ix_transaction_business_category', table_name='transaction')
    op.drop_index('ix_transaction_account_occurred_amount', table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('extraction')
    op.drop_table('declaration')
    op.drop_table('checklist_item')
    op.drop_table('agent_message')
    op.drop_table('readiness_score')
    op.drop_table('indicator')
    op.drop_table('gap')
    op.drop_table('document')
    op.drop_table('counterparty')
    op.drop_table('cost_event')
    op.drop_table('audit_event')
    op.drop_table('agent_session')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('business')
    # ### end Alembic commands ###
